#!/usr/bin/env bash
# This script installs and configures Nginx with a custom 404 page that says "Ceci n'est pas une page"

# Exit on any error
set -e

# Update packages
apt-get update -y

# Install nginx
apt-get install -y nginx

# Replace default index page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sed -i '/server_name _;/a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart nginx without systemctl
service nginx restart

